### ISSUE TITLE
Dropdown for datasets within collection may not be capturing the mouse, instead it's going to the image layer

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#449] opened 2023-06-30 01:37 UTC
There is a slight issue with layers in the collection dropdown. In the video below, when the mouse goes up and down in the dropdown on the left, it highlights the dataset as it moves up and down. But on the right, it doesn't highlight the dataset, and mouse clicks seem to go through to the image layer.

https://github.com/Kitware/UPennContrast/assets/13998824/31afb208-c185-41e8-a189-15b62af125e6

**Comment by bruyeret** [comment] 2023-07-24 13:57
I can't reproduce this issue
Do you still have it @arjunrajlab?
Otherwise you can close the issue

**Closed** 2023-09-24 15:12 UTC
Labels: bug
