### ISSUE TITLE
Data upload is very slow

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#187] opened 2022-02-11 15:09 UTC
For both Will and Arjun, data upload (Chrome, Mac M1 and Mac Intel) is about an order of magnitude slower than what we saw on Adrien's computer via Zoom.

**Comment by finetjul** [comment] 2022-07-22 13:25
On 2022/07/08: @finetjul and @luciemac will try to reproduce

**Comment by finetjul** [comment] 2022-07-22 14:00
@manthey is waiting for a mac machine

**Comment by finetjul** [comment] 2022-07-22 14:02
The issue is only when the front-end is a Mac (no matter the backend)

**Comment by manthey** [comment] 2022-08-26 13:32
Closing this as we seem to have resolved it for now.

**Closed by manthey** 2022-08-26 13:32 UTC
Labels: bug

**Comment by finetjul** [comment] 2022-09-02 17:33
@manthey for future referencing, can you please explain how the issue was resolved

**Comment by finetjul** [comment] 2022-09-23 07:31
It seems to be a fact that docker on Mac is slow.
There are some options ([example](https://accesto.com/blog/docker-on-mac-how-to-speed-it-up/))to speed-it up, but the best is simply to use Linux on production.
