### ISSUE TITLE
Issue with time offset causing a crash

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#307] opened 2022-11-03 12:48 UTC
There is an option, useful for time-lapse image visualization, for an offset in the time:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/13998824/199723926-7522f3a1-f53a-4f89-bcbf-409f698b28da.png">

<img width="293" alt="image" src="https://user-images.githubusercontent.com/13998824/199724510-ab520458-6c29-43d0-b16b-b0fa164cd00e.png">

Upon initially loading this dataset and visualizing with the offset layer, when you get to T=4 (so the red layer here would be T=5, which doesn't exist), the program crashes. If you reload the page, it works, though. I suspect it is trying to reference, on initial load, a frame which doesn't exist (T=5). 

Here's what it should look like, which does work properly for all T < max(T):
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/13998824/199724567-393e8520-45ee-4a91-8361-a2e8ebfe6086.png">

@manthey @finetjul

**Comment by manthey** [comment] 2022-11-04 13:28
At least on my system, it seems like the UI is caught in some sort of update loop.  In Chrome debugger, you can pause script execution and see that it is in a cycle of Vue updates.  This appears to be a change in  the last 4 weeks or so (commit 1d00db8 doesn't show the issue).

**Comment by manthey** [comment] 2022-11-04 14:18
Hmm....  I think I am wrong that the commit I mentioned works properly.  The specific actions I take to repeat the issue is to load the page with the non-offset axis low enough that the offset is within range, _change the offset_, then seek to a place where the offset is out of range.  If I _don't_ change the offset, the problem doesn't seem to occur.

**Comment by manthey** [comment] 2022-11-04 14:45
@bruyeret I'll have a fix for this shortly.

**Closed** 2022-11-07 13:18 UTC
Labels: bug
