### ISSUE TITLE
Bug with computation of intensities

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#170] opened 2021-12-17 13:41 UTC
Using the sample annotation worker, I noticed that the intensity is the same even when I tell it to compute across a different channel (in this case, A594 and Cy5):
![image](https://user-images.githubusercontent.com/13998824/146553127-b6577450-3637-4044-ad54-0f032e6c03f9.png)

**Comment by zjniu** [comment] 2022-01-28 07:23
I noticed that this was still happening half of the time.
<img width="561" alt="Screen Shot 2022-01-28 at 2 22 04 AM" src="https://user-images.githubusercontent.com/87096829/151504461-adcd99dc-7c56-487d-87d4-b56b327e9833.png">
The first half of the points are points from the GFP layer. The second half of the points are points from the DAPI layer. It seems like the issue is fixed on the GFP layer, but I am not sure why the DAPI points are still problematic.

**Comment by boucaud** [comment] 2022-01-28 09:54
The layer annotations are on is only taken into account if you set the property's layer to 'Any'. Otherwise if you've set a specific layer for a property, that will override annotation channels and only compute the property for the configured channel.

What are the property configurations for this example ?

**Comment by boucaud** [comment] 2022-02-08 10:32
This should be fixed now.

**Closed** 2023-09-24 15:42 UTC
Labels: bug, annotation-browser
