### ISSUE TITLE
Color-picker on brightfield image is diabled/not working (works sometimes, but not others).

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#84] opened 2021-05-14 12:47 UTC
<img width="427" alt="Screen Shot 2021-05-14 at 8 47 32 AM" src="https://user-images.githubusercontent.com/11461194/118272737-0dd12500-b491-11eb-8596-33a5d3024758.png">

**Comment by arjunrajlab** [comment] 2021-11-21 20:27
I have reproduced this issue. Maybe if a channel is assigned to FFFFFF (i.e., white), then moving the slider just doesn't do anything because everything is already saturated? Not sure.

**Closed** 2023-09-13 09:58 UTC
Labels: bug, short
