### ISSUE TITLE
Some TIFF files no longer import properly

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#609] opened 2023-12-02 19:34 UTC
@manthey I'm having a problem where these TIFF files do not upload and transcode properly. They used to work just fine, I believe, so not sure what happened. See the screenshot for the variable assignment (which is different than the default for these files). After upload, I assign variables and click submit, but it just spins on and on and never seems to start the transcoding. Not sure if this is related to the LIF and CZI file import issue.

Here are the files: https://www.dropbox.com/scl/fo/e5zp7lfgnx8kd52revmz8/h?rlkey=e5j43iwyviodzdnmwi9kp7p07&dl=0

@bruyeret Actually, an update: if I use just a single file from there, it still doesn't work. It seems to not know what to do with the variable assignment. I can click "Submit", but it spins, but I didn't even assign any variable. I wonder if there is some issue with the variable assignment code? Not sure. (I wonder if it is something new from the recent issue where you fixed the assignment code to remove an extra variable.)

NOTE: If you don't transcode the image, it proceeds to the view, but there is no image or data in there.

<img width="1199" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/6be621ad-e1bc-4c62-8a20-9d7c20771b04">

**Comment by bruyeret** [comment] 2023-12-04 14:18
It looks like a large image error
I can view the file on my computer
When I upload it to girder and try to "Use this file for large image", it doesn't work
In the error logs from girder there is this:
```
ERROR: 500 Error
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/girder/api/rest.py", line 649, in endpointDecorator
    val = fun(self, path, params)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder/api/rest.py", line 1238, in POST
    return self.handleRoute(method, path, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder/api/rest.py", line 977, in handleRoute
    val = handler(**kwargs)
          ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder/api/access.py", line 57, in wrapped
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder/api/rest.py", line 400, in wrapped
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder/api/rest.py", line 430, in wrapped
    val = fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder_large_image/rest/tiles.py", line 249, in createTiles
    return self.imageItemModel.createImageItem(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder_large_image/models/image_item.py", line 83, in createImageItem
    sourceName = girder_tilesource.getGirderTileSourceName(item, fileObj, noCache=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/girder_large_image/girder_tilesource.py", line 193, in getGirderTileSourceName
    if availableSources[sourceName].canRead(item, *args, **kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/large_image/large_image/tilesource/base.py", line 2977, in canRead
    cls(path, *args, **kwargs)
  File "/src/large_image/large_image/cache_util/cache.py", line 174, in __call__
    instance = super().__call__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/large_image_source_tifffile/__init__.py", line 141, in __init__
    self._findAssociatedImages()
  File "/venv/lib/python3.11/site-packages/large_image_source_tifffile/__init__.py", line 241, in _findAssociatedImages
    hashes = [p.hash for p in pagesInSeries if p.keyframe is not None]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/large_image_source_tifffile/__init__.py", line 241, in <listcomp>
    hashes = [p.hash for p in pagesInSeries if p.keyframe is not None]
                                               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyframe'
Additional info:
  Request URL: POST http://localhost:8080/api/v1/item/656dac93884f5f08ac2bc8f9/tiles
  Query string: 
  Remote IP: 172.17.0.1
  Request UID: 1131f830-c8e3-466e-8ba4-5ca5336c72f2
```

If it used to work, it looks like a regression of large image
Do you know if something changed recently in this part of the code @manthey ?

**Comment by manthey** [comment] 2023-12-05 13:59
This was a result of https://github.com/girder/large_image/pull/1333

Fix is in https://github.com/girder/large_image/pull/1396

**Comment by arjunrajlab** [comment] 2023-12-07 20:19
@manthey OK, I was able to load the full dataset:
https://www.dropbox.com/scl/fo/8nffbjuulk8o7qx5qdpmi/h?rlkey=n05zxfqzznjwdwdcg7j03m8w8&dl=0

But the problem now is that once it loads, the performance for scrubbing is really slow, much slower than it would be normally.

You can see what I mean here:

http://ec2-54-174-92-154.compute-1.amazonaws.com:8081/#/datasetView/6571cf8b70362a3363a4b681/view?z=32

It used to work fine on an instance of exactly the same size, so I'm not sure why it's so much slower now. I suspect maybe something on the front end? Perhaps related to https://github.com/Kitware/UPennContrast/issues/595 ??

**Comment by bruyeret** [comment] 2023-12-11 17:09
Is it fixed now that the reactivity issue has been fixed?

**Comment by arjunrajlab** [comment] 2023-12-11 17:10
Yes!

**Closed** 2023-12-11 17:11 UTC
Labels: bug
